server:
  port: 10001

spring:
  datasource:
    mysqldemo:
      username: root
      password: 1qaz2wsx
      url: jdbc:mysql://localhost:33060/demo?useUnicode=true&characterEncoding=UTF-8
      type: com.alibaba.druid.pool.DruidDataSource
    oracledemo:
      username: demo
      password: 1qaz2wsx
      url: jdbc:oracle:thin:@127.0.0.1:1521:xe
      type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    mysql:
      show-sql: true
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          dialect: org.hibernate.dialect.MySQL57Dialect
    oracle:
      show-sql: true
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          dialect: org.hibernate.dialect.Oracle12cDialect
