server:
  port: 10001

spring:
  datasource:
    username: root
    password: 1qaz2wsx
    url: jdbc:mysql://localhost:33060/demo?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

